### ISSUE TITLE
Help functionality should resemble that of man pages

### ISSUE THREAD

**Issue by SungMatt** [AY2324S1-CS2103-T16-1/tp#35]
Attempt to handle help with a commandhandler to parse input. Functionality should be similar to that of man pages in Linux.

Issue broken down into multiple parts

- [x] Create handler
- [x] Cases for both an empty help, and a specific help
- [x] Specific help -- display case specific help at any point of time.
- [ ] Link to the UI, issue #34.

**Comment by SungMatt** [comment]
Future possible extensions: Create a parser and flag out possible errors.
Other work to be done: Change the "Copy URL" button by the side to "Copy Example" for special help functions.
